[2024-11-06T14:48:17.686+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T14:48:17.727+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbnb_data_pipeline.Upload_To_S3 manual__2024-11-06T14:47:54.017068+00:00 [queued]>
[2024-11-06T14:48:17.743+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbnb_data_pipeline.Upload_To_S3 manual__2024-11-06T14:47:54.017068+00:00 [queued]>
[2024-11-06T14:48:17.743+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-06T14:48:17.769+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): Upload_To_S3> on 2024-11-06 14:47:54.017068+00:00
[2024-11-06T14:48:17.780+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=693) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-06T14:48:17.783+0000] {standard_task_runner.py:72} INFO - Started process 695 to run task
[2024-11-06T14:48:17.784+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'airbnb_data_pipeline', 'Upload_To_S3', 'manual__2024-11-06T14:47:54.017068+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/airbnb_dag.py', '--cfg-path', '/tmp/tmpow7yzhtf']
[2024-11-06T14:48:17.785+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask Upload_To_S3
[2024-11-06T14:48:17.874+0000] {task_command.py:467} INFO - Running <TaskInstance: airbnb_data_pipeline.Upload_To_S3 manual__2024-11-06T14:47:54.017068+00:00 [running]> on host 552c70a48aab
[2024-11-06T14:48:18.172+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbnb_data_pipeline' AIRFLOW_CTX_TASK_ID='Upload_To_S3' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T14:47:54.017068+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T14:47:54.017068+00:00'
[2024-11-06T14:48:18.175+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-06T14:48:18.176+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-06T14:48:18.177+0000] {logging_mixin.py:190} INFO - Current task name:Upload_To_S3 state:running start_date:2024-11-06 14:48:17.728106+00:00
[2024-11-06T14:48:18.177+0000] {logging_mixin.py:190} INFO - Dag name:airbnb_data_pipeline and current dag run status:running
[2024-11-06T14:48:18.178+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T14:48:21.633+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl/s3_upload_etl.py", line 30, in upload_file
    response = s3_client.upload_file(file_name, bucket, object_name)
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 's3.ServiceResource' object has no attribute 'upload_file'
[2024-11-06T14:48:21.710+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-06T14:48:21.711+0000] {logging_mixin.py:190} INFO - Task start:2024-11-06 14:48:17.728106+00:00 end:2024-11-06 14:48:21.705135+00:00 duration:3.977029
[2024-11-06T14:48:21.712+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Upload_To_S3> dag:<DAG: airbnb_data_pipeline> dagrun:<DagRun airbnb_data_pipeline @ 2024-11-06 14:47:54.017068+00:00: manual__2024-11-06T14:47:54.017068+00:00, state:running, queued_at: 2024-11-06 14:47:54.351209+00:00. externally triggered: True>
[2024-11-06T14:48:21.713+0000] {logging_mixin.py:190} INFO - Failure caused by 's3.ServiceResource' object has no attribute 'upload_file'
[2024-11-06T14:48:21.714+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=airbnb_data_pipeline, task_id=Upload_To_S3, run_id=manual__2024-11-06T14:47:54.017068+00:00, execution_date=20241106T144754, start_date=20241106T144817, end_date=20241106T144821
[2024-11-06T14:48:21.928+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T14:48:21.931+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 63 for task Upload_To_S3 ('s3.ServiceResource' object has no attribute 'upload_file'; 695)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl/s3_upload_etl.py", line 30, in upload_file
    response = s3_client.upload_file(file_name, bucket, object_name)
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 's3.ServiceResource' object has no attribute 'upload_file'
[2024-11-06T14:48:22.076+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-06T14:48:22.157+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
