[2024-10-31T09:39:58.194+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-31T09:39:58.319+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbnb_data_pipeline.check_and_download_data manual__2024-10-31T09:37:04.316000+00:00 [queued]>
[2024-10-31T09:39:58.436+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbnb_data_pipeline.check_and_download_data manual__2024-10-31T09:37:04.316000+00:00 [queued]>
[2024-10-31T09:39:58.442+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-31T09:39:58.533+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): check_and_download_data> on 2024-10-31 09:37:04.316000+00:00
[2024-10-31T09:39:58.712+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=303) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-31T09:39:58.716+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'airbnb_data_pipeline', 'check_and_download_data', 'manual__2024-10-31T09:37:04.316000+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/airbnb_dag.py', '--cfg-path', '/tmp/tmpw2_xwu8g']
[2024-10-31T09:39:58.721+0000] {standard_task_runner.py:72} INFO - Started process 314 to run task
[2024-10-31T09:39:58.722+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask check_and_download_data
[2024-10-31T09:39:59.088+0000] {task_command.py:467} INFO - Running <TaskInstance: airbnb_data_pipeline.check_and_download_data manual__2024-10-31T09:37:04.316000+00:00 [running]> on host 552c70a48aab
[2024-10-31T09:39:59.551+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbnb_data_pipeline' AIRFLOW_CTX_TASK_ID='check_and_download_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T09:37:04.316000+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-31T09:37:04.316000+00:00'
[2024-10-31T09:39:59.558+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-31T09:39:59.559+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-31T09:39:59.561+0000] {logging_mixin.py:190} INFO - Current task name:check_and_download_data state:running start_date:2024-10-31 09:39:58.322379+00:00
[2024-10-31T09:39:59.563+0000] {logging_mixin.py:190} INFO - Dag name:airbnb_data_pipeline and current dag run status:running
[2024-10-31T09:39:59.565+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-31T09:39:59.568+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-10-31T09:39:59.570+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 234, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py", line 421, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
TypeError: cannot unpack non-iterable datetime.date object
[2024-10-31T09:39:59.606+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-31T09:39:59.607+0000] {logging_mixin.py:190} INFO - Task start:2024-10-31 09:39:58.322379+00:00 end:2024-10-31 09:39:59.605153+00:00 duration:1.282774
[2024-10-31T09:39:59.609+0000] {logging_mixin.py:190} INFO - Task:<Task(BranchPythonOperator): check_and_download_data> dag:<DAG: airbnb_data_pipeline> dagrun:<DagRun airbnb_data_pipeline @ 2024-10-31 09:37:04.316000+00:00: manual__2024-10-31T09:37:04.316000+00:00, state:running, queued_at: 2024-10-31 09:37:04.481290+00:00. externally triggered: True>
[2024-10-31T09:39:59.610+0000] {logging_mixin.py:190} INFO - Failure caused by cannot unpack non-iterable datetime.date object
[2024-10-31T09:39:59.611+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=airbnb_data_pipeline, task_id=check_and_download_data, run_id=manual__2024-10-31T09:37:04.316000+00:00, execution_date=20241031T093704, start_date=20241031T093958, end_date=20241031T093959
[2024-10-31T09:39:59.655+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-31T09:39:59.659+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task check_and_download_data (cannot unpack non-iterable datetime.date object; 314)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 234, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py", line 421, in context_merge
    context.update(*args, **kwargs)
  File "<frozen _collections_abc>", line 987, in update
TypeError: cannot unpack non-iterable datetime.date object
[2024-10-31T09:39:59.739+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-31T09:40:00.084+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-31T09:40:00.099+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
